AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  droneActions:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: >-
        arn:aws:iam::075551390341:role/service-role/droneActions-role-3tv80mnv
      Environment:
        Variables:
          REGION: eu-west-1
          TABLE: droneTable
      RuntimePolicy:
        UpdateRuntimeOn: Auto
